# The hot path of the entire system. Every method here talks only to Redis.
# No Postgres reads, no Postgres writes. Correctness under concurrency comes
# from the fact that each Lua script executes atomically inside Redis: no
# other command can interleave between the inventory check and the decrement.
#
# Keys per flash sale:
#   flash_sale:{id}:inventory                 -> integer, units remaining
#   flash_sale:{id}:config                    -> hash { timeout_seconds, variant_id }
#   flash_sale:{id}:reservation:{buyer_id}    -> reservation token, TTL'd
#
# TTL policy: the reservation key gets a TTL of timeout + TTL_GRACE_SECONDS.
# The Sidekiq expiry worker (scheduled at exactly `timeout`) is the authority
# for restoring inventory. The TTL is only a backstop against a lost job, and
# it deliberately fails in the safe direction: if the worker never runs, a
# unit of inventory is leaked (undersell), never duplicated (oversell).
class InventoryReservationService
  TTL_GRACE_SECONDS = 60

  RESERVE_SCRIPT = <<~LUA.freeze
    -- KEYS[1] inventory counter
    -- KEYS[2] this buyer's reservation key
    -- KEYS[3] sale config hash
    -- ARGV[1] reservation token (uuid, generated by the caller)
    local inventory = redis.call('GET', KEYS[1])
    if not inventory then
      return {0, 'not_active'}
    end
    if redis.call('EXISTS', KEYS[2]) == 1 then
      return {0, 'already_reserved'}
    end
    if tonumber(inventory) <= 0 then
      return {0, 'sold_out'}
    end
    local timeout = tonumber(redis.call('HGET', KEYS[3], 'timeout_seconds')) or 300
    redis.call('DECR', KEYS[1])
    redis.call('SET', KEYS[2], ARGV[1], 'EX', timeout + #{TTL_GRACE_SECONDS})
    return {1, ARGV[1], timeout}
  LUA

  # Release only fires if the key still holds the exact token we issued. This
  # is what makes the expiry worker safe to run at any time: if the webhook
  # already confirmed (and deleted) the reservation, GET returns nil, the
  # comparison fails, and inventory is not restored.
  RELEASE_SCRIPT = <<~LUA.freeze
    -- KEYS[1] inventory counter, KEYS[2] reservation key, ARGV[1] token
    local current = redis.call('GET', KEYS[2])
    if current == ARGV[1] then
      redis.call('DEL', KEYS[2])
      redis.call('INCR', KEYS[1])
      return 1
    end
    return 0
  LUA

  # Confirm deletes the reservation key without touching inventory: the unit
  # is sold, the decrement from reserve() is now permanent. Deleting the key
  # is also what disarms the pending expiry worker.
  CONFIRM_SCRIPT = <<~LUA.freeze
    -- KEYS[1] reservation key, ARGV[1] token
    local current = redis.call('GET', KEYS[1])
    if current == ARGV[1] then
      redis.call('DEL', KEYS[1])
      return 1
    end
    return 0
  LUA

  Result = Struct.new(:reserved, :reason, :token, :timeout_seconds, keyword_init: true) do
    def reserved?
      reserved
    end
  end

  def initialize(redis: RedisConnection.client)
    @redis = redis
  end

  # Called once, at sale activation. NX so a double-fired activation job can
  # never reset the counter mid-sale.
  def activate(flash_sale)
    @redis.set(flash_sale.inventory_key, flash_sale.inventory_count, nx: true)
    @redis.hset(
      flash_sale.config_key,
      "timeout_seconds", flash_sale.reservation_timeout_seconds,
      "variant_id", flash_sale.shopify_variant_id
    )
  end

  def reserve(flash_sale_id:, buyer_id:, token: SecureRandom.uuid)
    status, value, timeout = run_script(
      RESERVE_SCRIPT,
      keys: [inventory_key(flash_sale_id), reservation_key(flash_sale_id, buyer_id), config_key(flash_sale_id)],
      argv: [token]
    )

    if status == 1
      Result.new(reserved: true, token: value, timeout_seconds: timeout.to_i)
    else
      Result.new(reserved: false, reason: value)
    end
  end

  # Returns true when inventory was actually restored.
  def release(flash_sale_id:, buyer_id:, token:)
    run_script(
      RELEASE_SCRIPT,
      keys: [inventory_key(flash_sale_id), reservation_key(flash_sale_id, buyer_id)],
      argv: [token]
    ) == 1
  end

  # Returns true when the pending reservation was consumed by this confirmation.
  def confirm(flash_sale_id:, buyer_id:, token:)
    run_script(
      CONFIRM_SCRIPT,
      keys: [reservation_key(flash_sale_id, buyer_id)],
      argv: [token]
    ) == 1
  end

  def current_inventory(flash_sale_id)
    value = @redis.get(inventory_key(flash_sale_id))
    value && Integer(value)
  end

  private

  def inventory_key(id)   = "flash_sale:#{id}:inventory"
  def config_key(id)      = "flash_sale:#{id}:config"
  def reservation_key(id, buyer_id) = "flash_sale:#{id}:reservation:#{buyer_id}"

  # EVALSHA with a lazy fallback to EVAL: after the first call (or a Redis
  # restart that empties the script cache) the script body never crosses the
  # wire again.
  def run_script(script, keys:, argv:)
    sha = script_shas[script] ||= Digest::SHA1.hexdigest(script)
    @redis.evalsha(sha, keys: keys, argv: argv)
  rescue Redis::CommandError => e
    raise unless e.message.include?("NOSCRIPT")

    @redis.eval(script, keys: keys, argv: argv)
  end

  def script_shas
    @script_shas ||= {}
  end
end
